version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env.production
    environment:
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
